# site settings

title: Chaw| A Programmer
description: Portfolio site by Chaw 
taglong: Portfolio site by Chaw Thiri San
tagshort: Chaw Chaw's Site
url: https://chaw.compare/
baseurl: ""
permalink: pretty
repo: https://github.com/chaw-thiri/chaw-thiri.github.io

# author settings

author:
  name: Chaw
  email: chawthiri177@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: chaw-thiri
  instagram: chaw_chaw_01
  linkedin: Chaw Thiri San


# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
